# Generated by Django 6.0.1 on 2026-01-15 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("location_type", models.CharField(blank=True, default="", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BAG_INTERVENTION", "Sac d'intervention"),
                            ("BAG_OXY", "Sac d'oxygénothérapie"),
                            ("BAG_FIRST_AID", "Sac de premiers secours"),
                            ("VEHICLE_VPSP", "VPSP"),
                            ("OXYGEN_CYLINDER", "Bouteille O2"),
                            ("RESERVE_CASE", "Malle/Sac réserve"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("identifier", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="containers",
                        to="organizations.structure",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="containers",
                        to="inventory.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories",
                        to="inventory.container",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories",
                        to="organizations.structure",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_inventories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, default="", max_length=64)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                ("is_consumable", models.BooleanField(default=True)),
                ("requires_expiry", models.BooleanField(default=False)),
                ("requires_lot_number", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expected_qty", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("counted_qty", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.inventorysession",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(blank=True, default="", max_length=64)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("LOT_A", "Lot A (secours)"),
                            ("LOT_B", "Lot B (1er secours)"),
                            ("LOT_C", "Lot C (intervention)"),
                            ("VPSP", "VPSP"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("next_check_due_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="READY", max_length=32)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="inventory.container",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="inventory.lottemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("ADMIN_DOCS", "Administratif/Documents"),
                            ("COMMS", "Communication"),
                            ("PROTECTION", "Protection/Hygiène/Sécurité"),
                            ("VITALS", "Bilans"),
                            ("WOUNDS", "Hémorragies/Plaies"),
                            ("TRAUMA", "Immobilisations/Trauma"),
                            ("RESUSC", "Réanimation"),
                            ("DIVERS", "Divers"),
                            ("SPECIFIC_KITS", "Kits spécifiques"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.lottemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="organizations.structure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="inventory.site",
            ),
        ),
        migrations.CreateModel(
            name="StockLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.batch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "lot_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_lines",
                        to="inventory.lotinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrée"),
                            ("OUT", "Sortie"),
                            ("TRANSFER", "Transfert"),
                            ("ADJUST", "Ajustement"),
                            ("CONSUME", "Consommation mission"),
                            ("RESTOCK", "Réassort"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="inventory.lotinstance",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="organizations.structure",
                    ),
                ),
                (
                    "to_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="inventory.lotinstance",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "name"], name="inventory_i_organiz_006385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "sku"], name="inventory_i_organiz_6ca2ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_item_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryline",
            constraint=models.UniqueConstraint(
                fields=("session", "item"), name="uniq_inventory_line_per_session_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_qty__gte", 0)), name="check_expected_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_qty__gte", 0)), name="check_counted_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["item", "expires_at"], name="inventory_b_item_id_f6da20_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("item", "lot_number", "expires_at"),
                name="uniq_batch_per_item_number_expiry",
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["structure", "type"], name="inventory_c_structu_d786d8_idx"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["structure", "identifier"], name="inventory_c_structu_1363f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="container",
            constraint=models.UniqueConstraint(
                fields=("structure", "identifier"), name="uniq_container_identifier_per_structure"
            ),
        ),
        migrations.AddIndex(
            model_name="lottemplate",
            index=models.Index(
                fields=["organization", "code", "version"], name="inventory_l_organiz_65bb58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lottemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "version"),
                name="uniq_template_per_org_code_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="lotinstance",
            constraint=models.UniqueConstraint(
                fields=("template", "container"), name="uniq_template_container"
            ),
        ),
        migrations.AddConstraint(
            model_name="lottemplateitem",
            constraint=models.UniqueConstraint(
                fields=("template", "group", "item"), name="uniq_template_group_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="lottemplateitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_qty__gte", 0)), name="check_expected_qty_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["structure", "name"], name="inventory_s_structu_a5e1f6_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["site", "name"], name="inventory_l_site_id_338dff_idx"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="uniq_location_name_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockline",
            constraint=models.UniqueConstraint(
                fields=("lot_instance", "item", "batch"), name="uniq_stockline_per_lot_item_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="check_stock_quantity_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="check_movement_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("from_lot__isnull", False), ("to_lot__isnull", False), ("type", "TRANSFER")
                    ),
                    models.Q(("to_lot__isnull", False), ("type", "IN")),
                    models.Q(("from_lot__isnull", False), ("type", "OUT")),
                    ("type", "ADJUST"),
                    models.Q(("from_lot__isnull", False), ("type", "CONSUME")),
                    models.Q(("to_lot__isnull", False), ("type", "RESTOCK")),
                    _connector="OR",
                ),
                name="check_movement_lot_consistency",
            ),
        ),
    ]
