# Generated by Django 6.0.1 on 2026-01-15 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("TERRITORIAL", "Territorial"),
                            ("LOCAL", "Local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="organizations.structure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Lecteur"),
                            ("REFERENT", "Référent matériel"),
                            ("ADMIN", "Admin structure"),
                        ],
                        default="VIEWER",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("STAGIAIRE", "Stagiaire"),
                            ("PSE1", "PSE1"),
                            ("PSE2", "PSE2"),
                            ("CI", "Chef d'Intervention"),
                            ("CDPE", "Chef DPS petite envergure"),
                            ("CDMGE", "Chef DPS moyenne/grande envergure"),
                        ],
                        default="STAGIAIRE",
                        max_length=20,
                    ),
                ),
                ("is_fc_up_to_date", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.structure",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="structure",
            index=models.Index(
                fields=["organization", "level"], name="organizatio_organiz_51e5d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="structure",
            index=models.Index(fields=["parent"], name="organizatio_parent__9d89b9_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["structure", "role"], name="organizatio_structu_35621f_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["structure", "is_active"], name="organizatio_structu_09eb17_idx"
            ),
        ),
    ]
